### ISSUE TITLE
In production build zoom widget has wrong width

### ISSUE THREAD

**Issue by sitek94** [sitek94/react-d3-interactive-globe#86]
This shouldn't be applied
```css
.MuiButtonGroup-grouped {
    min-width: 40px;
}
```
